# Generated by Django 5.2.7 on 2025-11-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravaathlete',
            name='ftp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
