# Generated by Django 5.2.7 on 2025-11-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaauth', '0002_alter_stravaathlete_ftp'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravaathlete',
            name='activities_last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
