# Generated by Django 5.2.7 on 2025-11-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaauth', '0003_stravaathlete_activities_last_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravaathlete',
            name='access_token',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='stravaathlete',
            name='athelete_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stravaathlete',
            name='expires_at_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stravaathlete',
            name='measurement_preference',
            field=models.CharField(blank=True, choices=[('F', 'Feet'), ('M', 'Meters')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='stravaathlete',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='stravaathlete',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
