# Generated by Django 5.2.7 on 2025-11-17 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_id', models.IntegerField()),
                ('name', models.CharField(blank=True, null=True)),
                ('elapsed_time', models.IntegerField()),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_id', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('start_date_local', models.DateTimeField()),
                ('timezone', models.CharField(max_length=100)),
                ('utc_offset', models.IntegerField()),
                ('location_city', models.CharField(blank=True, max_length=125, null=True)),
                ('location_state', models.CharField(blank=True, max_length=125, null=True)),
                ('location_country', models.CharField(blank=True, max_length=125, null=True)),
                ('achievement_count', models.IntegerField()),
                ('kudos_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
                ('athlete_count', models.IntegerField()),
                ('photo_count', models.IntegerField()),
                ('device_name', models.CharField(blank=True, max_length=125, null=True)),
                ('trainer', models.BooleanField(default=False)),
                ('commute', models.BooleanField(default=False)),
                ('manual', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('flagged', models.BooleanField(default=False)),
                ('gear_id', models.CharField(blank=True, max_length=125, null=True)),
                ('from_accepted_tag', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovingActivity',
            fields=[
                ('baseactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='strava.baseactivity')),
                ('moving_time', models.IntegerField()),
                ('sport_type', models.CharField(choices=[('CF', 'Crossfit'), ('E', 'Elliptical'), ('RC', 'Rock Climbing'), ('STS', 'Stair Stepper'), ('VR', 'Virtual Ride'), ('VRU', 'Virtual Run'), ('WT', 'Weight Training'), ('WO', 'Workout'), ('Y', 'Yoga'), ('AS', 'Alpine Ski'), ('BS', 'Backcountry Ski'), ('C', 'Canoeing'), ('EBR', 'E-Bike Ride'), ('G', 'Golf'), ('HC', 'Handcycle'), ('H', 'Hike'), ('IS', 'Ice Skate'), ('ILS', 'Inline Skate'), ('K', 'Kayaking'), ('KS', 'Kitesurf'), ('NS', 'Nordic Ski'), ('R', 'Ride'), ('RS', 'Roller Ski'), ('ROW', 'Rowing'), ('R', 'Running'), ('S', 'Sailing'), ('SB', 'Skateboard'), ('SNB', 'Snowboard'), ('SS', 'Snowshoe'), ('SO', 'Soccer'), ('SUP', 'Stand Up Paddling'), ('SU', 'Surfing'), ('SW', 'Swim'), ('V', 'Velomobile'), ('W', 'Walk'), ('WC', 'Wheelchair'), ('WS', 'Windsurf')], max_length=10)),
                ('total_elevation_gain', models.FloatField()),
                ('start_langitude', models.FloatField(blank=True, null=True)),
                ('start_longitude', models.FloatField(blank=True, null=True)),
                ('end_langitude', models.FloatField(blank=True, null=True)),
                ('end_longitude', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField()),
                ('average_speed', models.FloatField()),
                ('max_speed', models.FloatField()),
                ('average_cadence', models.FloatField(blank=True, null=True)),
                ('average_watts', models.FloatField(blank=True, null=True)),
                ('weighted_average_watts', models.IntegerField(blank=True, null=True)),
                ('kilojoules', models.FloatField(blank=True, null=True)),
                ('device_watts', models.BooleanField(default=False)),
                ('has_heartrate', models.BooleanField(default=False)),
                ('average_heartrate', models.FloatField(blank=True, null=True)),
                ('max_heartrate', models.FloatField(blank=True, null=True)),
                ('max_watts', models.IntegerField(blank=True, null=True)),
                ('pr_count', models.IntegerField(default=0)),
                ('total_photo_count', models.IntegerField(default=0)),
                ('has_kudoed', models.BooleanField(default=False)),
                ('suffer_score', models.FloatField(blank=True, null=True)),
            ],
            bases=('strava.baseactivity',),
        ),
        migrations.CreateModel(
            name='NonMovingActivity',
            fields=[
                ('baseactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='strava.baseactivity')),
                ('sport_type', models.CharField(choices=[('CF', 'Crossfit')], max_length=10)),
            ],
            bases=('strava.baseactivity',),
        ),
        migrations.CreateModel(
            name='StationaryMovingActivity',
            fields=[
                ('baseactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='strava.baseactivity')),
                ('distance', models.FloatField()),
                ('sport_type', models.CharField(choices=[('CF', 'Crossfit'), ('E', 'Elliptical'), ('RC', 'Rock Climbing'), ('STS', 'Stair Stepper'), ('VR', 'Virtual Ride'), ('VRU', 'Virtual Run'), ('WT', 'Weight Training'), ('WO', 'Workout'), ('Y', 'Yoga')], max_length=10)),
                ('average_speed', models.FloatField()),
                ('max_speed', models.FloatField()),
                ('average_cadence', models.FloatField(blank=True, null=True)),
                ('average_watts', models.FloatField(blank=True, null=True)),
                ('weighted_average_watts', models.IntegerField(blank=True, null=True)),
                ('kilojoules', models.FloatField(blank=True, null=True)),
                ('device_watts', models.BooleanField(default=False)),
                ('has_heartrate', models.BooleanField(default=False)),
                ('average_heartrate', models.FloatField(blank=True, null=True)),
                ('max_heartrate', models.FloatField(blank=True, null=True)),
                ('max_watts', models.IntegerField(blank=True, null=True)),
                ('pr_count', models.IntegerField(default=0)),
                ('total_photo_count', models.IntegerField(default=0)),
                ('has_kudoed', models.BooleanField(default=False)),
                ('suffer_score', models.FloatField(blank=True, null=True)),
            ],
            bases=('strava.baseactivity',),
        ),
        migrations.CreateModel(
            name='ActivityMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_id', models.CharField(max_length=125)),
                ('polyline', models.TextField()),
                ('summary_polyline', models.TextField()),
                ('moving_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strava.movingactivity')),
            ],
        ),
    ]
