# Generated by Django 5.2.7 on 2025-11-25 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0002_alter_movingactivity_sport_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movingactivity',
            old_name='end_langitude',
            new_name='end_latitude',
        ),
        migrations.RenameField(
            model_name='movingactivity',
            old_name='start_langitude',
            new_name='start_latitude',
        ),
        migrations.AlterField(
            model_name='activitymap',
            name='moving_activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='strava.movingactivity'),
        ),
        migrations.AlterField(
            model_name='movingactivity',
            name='sport_type',
            field=models.CharField(choices=[('CF', 'Crossfit'), ('HIT', 'High Intensity Interval Training'), ('WT', 'Weight Training'), ('WO', 'Workout'), ('Y', 'Yoga'), ('P', 'Pilates'), ('E', 'Elliptical'), ('RC', 'Rock Climbing'), ('STS', 'Stair Stepper'), ('VR', 'Virtual Ride'), ('VRU', 'Virtual Run'), ('VRO', 'VirtualRow'), ('AS', 'Alpine Ski'), ('BS', 'Backcountry Ski'), ('C', 'Canoeing'), ('EBR', 'E-Bike Ride'), ('G', 'Golf'), ('HC', 'Handcycle'), ('H', 'Hike'), ('IS', 'Ice Skate'), ('ILS', 'Inline Skate'), ('K', 'Kayaking'), ('KS', 'Kitesurf'), ('NS', 'Nordic Ski'), ('R', 'Ride'), ('RS', 'Roller Ski'), ('ROW', 'Rowing'), ('RU', 'Running'), ('S', 'Sailing'), ('SB', 'Skateboard'), ('SNB', 'Snowboard'), ('SS', 'Snowshoe'), ('SO', 'Soccer'), ('SUP', 'Stand Up Paddling'), ('SU', 'Surfing'), ('SW', 'Swim'), ('V', 'Velomobile'), ('W', 'Walk'), ('WC', 'Wheelchair'), ('WS', 'Windsurf')], max_length=10),
        ),
    ]
