# Generated by Django 5.2.7 on 2025-11-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0003_rename_end_langitude_movingactivity_end_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonmovingactivity',
            name='has_kudoed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nonmovingactivity',
            name='total_photo_count',
            field=models.IntegerField(default=0),
        ),
    ]
