# Generated by Django 5.2.7 on 2025-11-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0004_nonmovingactivity_has_kudoed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movingactivity',
            name='sport_type',
            field=models.CharField(choices=[('CF', 'Crossfit'), ('HIT', 'High Intensity Interval Training'), ('WT', 'Weight Training'), ('WO', 'Workout'), ('Y', 'Yoga'), ('P', 'Pilates'), ('E', 'Elliptical'), ('RC', 'Rock Climbing'), ('STS', 'Stair Stepper'), ('VR', 'Virtual Ride'), ('VRU', 'Virtual Run'), ('VRO', 'VirtualRow'), ('AS', 'Alpine Ski'), ('BS', 'Backcountry Ski'), ('C', 'Canoeing'), ('EBR', 'E-Bike Ride'), ('G', 'Golf'), ('GR', 'Gravel Ride'), ('HC', 'Handcycle'), ('H', 'Hike'), ('IS', 'Ice Skate'), ('ILS', 'Inline Skate'), ('K', 'Kayaking'), ('KS', 'Kitesurf'), ('NS', 'Nordic Ski'), ('R', 'Ride'), ('RS', 'Roller Ski'), ('ROW', 'Rowing'), ('RU', 'Running'), ('S', 'Sailing'), ('SB', 'Skateboard'), ('SNB', 'Snowboard'), ('SS', 'Snowshoe'), ('SO', 'Soccer'), ('SUP', 'Stand Up Paddling'), ('SU', 'Surfing'), ('SW', 'Swim'), ('V', 'Velomobile'), ('W', 'Walk'), ('WC', 'Wheelchair'), ('WS', 'Windsurf')], max_length=10),
        ),
    ]
